human:
  human: &title HUMAN 2024
  full_name: &full_name 2nd Workshop on Advances in Human-Centric Experiments in Software Engineering
  url: https://human-conf.github.io/human24/
  year: &year 2024
  saner: &saner SANER 2024
  saner_url: &saner_url https://conf.researchr.org/home/saner-2024
  dates:
    submission: November 10, 2023
    notification: December 8, 2023
    camera_ready: January 12, 2024
    workshop: 12 March, 2024
  easychair_url: https://easychair.org/conferences/?conf=human24
  hashtag: human_workshop2024
  
title: *title
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: *saner
      icon: "fas fa-chalkboard-teacher"
      url: *saner_url
    - label: HUMAN-series
      icon: "fas fa-home"
      url: https://human-conf.github.io

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
      author_profile: false
      header:
        overlay_color: "#000"
        overlay_filter: "0.5"
        overlay_image: /assets/images/human_banner_friendly.jpg
      excerpt: *full_name


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
